insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Elbert', 'Gonnet', '453-67-0208', 'Engineer II', 32, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Melinde', 'Marjoram', '107-84-2427', 'Mechanical Systems Engineer', 38, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Delmor', 'Kuhnwald', '690-10-7800', 'Editor', 33, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Honoria', 'Jasiak', '687-41-1536', 'Project Manager', 40, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Simona', 'Wilbraham', '502-70-2331', 'Assistant Manager', 33, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Margy', 'Ambrose', '239-65-8354', 'Developer IV', 39, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Averell', 'Ruggles', '217-50-1060', 'Programmer I', 35, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Edmon', 'MacHoste', '714-50-7526', 'Project Manager', 34, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Catarina', 'Davidowsky', '775-83-4109', 'Structural Engineer', 33, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Christiane', 'Lambrook', '726-25-7569', 'Pharmacist', 31, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Shauna', 'Bruford', '686-49-2031', 'Web Developer II', 36, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Rachel', 'Scrase', '253-11-7670', 'Director of Sales', 32, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Melba', 'Greenleaf', '244-80-1606', 'Sales Associate', 38, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Barbey', 'Kanzler', '315-94-4591', 'Assistant Professor', 36, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Lesya', 'Pinsent', '497-47-2951', 'Paralegal', 37, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Sybil', 'Sacase', '815-49-6744', 'VP Accounting', 35, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Merrill', 'Scoon', '155-91-7055', 'Research Nurse', 33, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Jervis', 'McDermot', '414-18-6473', 'Database Administrator III', 30, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Gwennie', 'Brantl', '463-93-9150', 'Staff Scientist', 38, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Fallon', 'Densham', '196-44-5772', 'Research Nurse', 37, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Ashley', 'Pering', '400-43-0576', 'Dental Hygienist', 36, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Raoul', 'Bedding', '787-74-0979', 'Graphic Designer', 32, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Fletch', 'Western', '117-58-6852', 'GIS Technical Architect', 30, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Sly', 'de Quesne', '143-62-1131', 'Administrative Officer', 38, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Deana', 'Meineking', '390-25-3741', 'Biostatistician I', 34, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Wheeler', 'Budibent', '739-79-9580', 'Automation Specialist IV', 38, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Amery', 'Rudgley', '776-03-4945', 'Administrative Assistant III', 35, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Gracie', 'Bewlay', '887-30-3047', 'Mechanical Systems Engineer', 38, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Friedrick', 'Leahey', '385-83-9553', 'Chief Design Engineer', 31, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Brynn', 'Macewan', '403-78-6609', 'Registered Nurse', 35, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Sarine', 'Deporte', '102-51-3882', 'Senior Cost Accountant', 36, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Carlye', 'Bodle', '111-14-3732', 'Operator', 33, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Constanta', 'St. Aubyn', '129-26-9259', 'Software Engineer II', 38, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Lucinda', 'Stafford', '626-39-0496', 'Biostatistician II', 37, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Claiborne', 'Goodram', '570-33-4172', 'VP Accounting', 39, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Winnie', 'Crummay', '869-88-4731', 'Data Coordiator', 32, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Marleen', 'Seton', '344-60-4675', 'Senior Developer', 40, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Gwenora', 'Hammonds', '411-04-3952', 'Business Systems Development Analyst', 39, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Philis', 'Ridde', '174-86-1945', 'Environmental Tech', 36, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Claudina', 'Innman', '640-74-2827', 'Automation Specialist II', 31, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Lorrayne', 'Cockcroft', '643-74-6865', 'Editor', 36, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Viviene', 'Moreno', '436-42-2172', 'Recruiter', 39, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Wyndham', 'Van Leijs', '805-76-4869', 'Staff Scientist', 36, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Theressa', 'Winridge', '899-10-9122', 'Chief Design Engineer', 39, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Oneida', 'Grayer', '617-46-3293', 'Chemical Engineer', 34, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Berti', 'Hostan', '534-04-4064', 'Internal Auditor', 30, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Doroteya', 'Jobb', '466-76-7142', 'Help Desk Operator', 39, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('De', 'Clackers', '846-46-9271', 'Chief Design Engineer', 31, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Kalindi', 'Linkie', '227-44-9111', 'Software Engineer II', 31, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Freedman', 'Getsham', '768-26-6343', 'Office Assistant II', 39, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Meredeth', 'Scole', '285-77-7975', 'Senior Financial Analyst', 34, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Thomasine', 'Pierson', '749-68-6829', 'Quality Control Specialist', 35, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Ealasaid', 'Londors', '278-76-7656', 'Registered Nurse', 34, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Lucy', 'Maybury', '897-38-4178', 'Business Systems Development Analyst', 34, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Alvy', 'Traves', '374-64-6212', 'Geological Engineer', 34, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Rosanna', 'Parfett', '764-45-7824', 'Media Manager III', 31, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Petronilla', 'McBeath', '267-56-9830', 'Paralegal', 37, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Averil', 'Moral', '264-64-9885', 'Compensation Analyst', 31, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Constantine', 'Knoble', '222-20-7705', 'Research Nurse', 40, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Cathie', 'Oakeshott', '458-51-2192', 'Research Nurse', 34, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Papageno', 'Torr', '505-43-7767', 'Recruiter', 30, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Carce', 'McConnachie', '205-66-6513', 'Chemical Engineer', 34, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Mil', 'Menelaws', '667-91-8907', 'Software Engineer I', 38, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Kenn', 'Andreone', '817-87-3230', 'Compensation Analyst', 34, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Donielle', 'Bolesma', '771-14-7812', 'Mechanical Systems Engineer', 36, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Tamera', 'Flear', '342-36-8921', 'Desktop Support Technician', 34, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Sarene', 'McCrohon', '103-49-0856', 'Assistant Manager', 38, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Fanya', 'Hartus', '300-83-0576', 'Senior Developer', 32, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Spence', 'Scarisbrick', '566-90-8898', 'Accounting Assistant IV', 36, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Ty', 'Jinda', '697-83-0973', 'Professor', 32, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Nicolai', 'Salerg', '703-90-4348', 'Civil Engineer', 34, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Catriona', 'Hintzer', '767-73-5013', 'Chief Design Engineer', 38, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Dede', 'Lawrie', '373-44-1843', 'Junior Executive', 39, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Ritchie', 'Walbrun', '401-06-2155', 'Budget/Accounting Analyst IV', 39, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Clair', 'Smallcombe', '189-42-7705', 'Food Chemist', 37, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Maximo', 'Parres', '133-08-5593', 'Professor', 32, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Bernadine', 'Forsbey', '707-44-4806', 'Automation Specialist I', 40, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Deane', 'Toby', '548-69-4322', 'Junior Executive', 34, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Waverly', 'Colvie', '626-04-8436', 'Associate Professor', 34, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Donnamarie', 'Cockell', '760-65-7345', 'Structural Analysis Engineer', 38, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Jeannette', 'Borchardt', '878-27-1017', 'Cost Accountant', 30, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Bank', 'Pollard', '494-96-9961', 'Senior Cost Accountant', 34, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Ruthy', 'Harbertson', '590-88-7442', 'Office Assistant II', 40, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Ileana', 'Persitt', '258-67-9916', 'Research Associate', 37, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Bennie', 'Voyce', '820-45-5036', 'Speech Pathologist', 35, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Joeann', 'Martensen', '635-83-3485', 'Chemical Engineer', 34, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Thaddeus', 'Lethabridge', '847-51-9127', 'Help Desk Technician', 38, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Curcio', 'Mayor', '299-39-9178', 'Senior Cost Accountant', 39, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Porty', 'Banister', '711-63-3590', 'Payment Adjustment Coordinator', 30, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Hertha', 'Vanns', '698-58-0133', 'Analyst Programmer', 34, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Adria', 'Saunton', '348-17-3264', 'Human Resources Assistant IV', 35, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Ruby', 'Iacopetti', '691-51-1040', 'Safety Technician III', 30, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Demeter', 'Garmanson', '669-91-9060', 'Research Associate', 30, 1);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Elroy', 'Freed', '628-64-3804', 'Administrative Officer', 35, 2);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Sophia', 'Wallbridge', '443-66-9502', 'Clinical Specialist', 33, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Gavan', 'MacGilmartin', '261-51-5175', 'Compensation Analyst', 40, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Sibby', 'Degoy', '766-45-7342', 'Marketing Assistant', 34, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Bo', 'Costigan', '790-69-6837', 'Marketing Assistant', 37, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Alvis', 'Zorn', '587-16-9619', 'Librarian', 39, 3);
insert into Employee (Employee_Fname, Employee_Lname, Employee_SSN, Job, Hours_per_week, LibraryId) values ('Antoinette', 'Lossman', '816-16-6942', 'Pharmacist', 30, 3);
